export { default as Home } from "./Home"
export { default as NotFound } from "./NotFound"
export { default as TermsAndConditions } from "./Terms-And-Conditions"
export { default as PrivacyPolicy } from "./Privacy-Policy"
export { default as HelpCenter } from "./Help-Center"
